#pragma config(Sensor, dgtl12, solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftArm,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		//right side
		motor[backRight] = vexRT[Ch2];
		motor[frontRight] = vexRT[Ch2];
		//left side
		motor[backLeft] = -vexRT[Ch3];
		motor[frontLeft] = -vexRT[Ch3];

		//lift
		motor[leftLift] = vexRT[Ch2Xmtr2];
		motor[rightLift] =  vexRT[Ch2Xmtr2];

		//arm
		motor[rightArm] = vexRT[Ch3Xmtr2];
		motor[LeftArm] = vexRT[Ch3Xmtr2];


		if(vexRT[Btn6UXmtr2])
		{
			motor[claw] = 127;
		}
		else if(vexRT[Btn6DXmtr2])
		{
			motor[claw] = -127;
		}
		else{
			motor[claw] = 0;
		}

		if(vexRT[Btn6U])
		{
			SensorValue[solenoid] = 1;
		}
		else if(vexRT[Btn6D])
		{
			SensorValue[solenoid] = 0;
		}
	}

}
